name = "biliyor-muydunuz-instagram-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "instagram_biliyor_muydunuz_db"
database_id = "0d5dffa3-eae2-4b95-b4b2-e358bc0a9bf1"
